const initialWorkouts=[
 {id:'w1',date:'2026-06-23',time:'11:00',type:'low',title:'low intensity',treadmill:{mode:'walk',amount:'2.5–3',unit:'km'},exercises:[['row',3,'10'],['seated dumbbell bicep curls',3,'10'],['squats',3,'8–10'],['seated calf raises',3,'15']]},
 {id:'w2',date:'2026-06-25',time:'11:00',type:'moderate',title:'repetition · moderate intensity',treadmill:{mode:'walk',amount:'2.5–3',unit:'km'},exercises:[['row',3,'10'],['seated dumbbell bicep curls',3,'10'],['squats',3,'8–10'],['seated calf raises',3,'15']]},
 {id:'w3',date:'2026-06-27',time:'15:30',type:'recovery',title:'recovery session',treadmill:{mode:'walk',amount:'30',unit:'mins'},exercises:[['swim or bike ride',1,'30']]}
];
const storageKey='workout-plan-v3';
let workouts=JSON.parse(localStorage.getItem(storageKey)||'null')||initialWorkouts;
let calendarCursor=new Date('2026-06-01T12:00:00');
let weekCursor=weekStart(bangkokNow().iso);
let originalSnapshot='';
let pendingClose=false;
let draggedId=null;
let touchDrag=null;
let suppressClickUntil=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const months=['january','february','march','april','may','june','july','august','september','october','november','december'];
const dayNames=['sun','mon','tue','wed','thu','fri','sat'];
const todayIso=bangkokNow().iso;

function bangkokNow(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23',minute:'2-digit',weekday:'long'}).formatToParts(new Date());const get=t=>parts.find(p=>p.type===t)?.value;return{iso:`${get('year')}-${get('month')}-${get('day')}`,hour:+get('hour'),minute:get('minute'),weekday:get('weekday')}}
function dateOf(iso){return new Date(`${iso}T12:00:00`)}
function isoOf(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function persist(){localStorage.setItem(storageKey,JSON.stringify(workouts))}
function lower(s=''){return s.toLocaleLowerCase('en')}
function setGreeting(){const n=bangkokNow();let period,icon;if(n.hour>=5&&n.hour<12){period='morning';icon='sun'}else if(n.hour>=12&&n.hour<16){period='afternoon';icon='day'}else if(n.hour>=16&&n.hour<22){period='evening';icon='evening'}else{period='night';icon='night'}const heading=$('#greetingText');heading.setAttribute('aria-label',`good ${period}`);heading.innerHTML=`<span class="greeting-word">g<span class="letter-icon ${icon}" aria-hidden="true"></span>od</span><span class="greeting-period">${period}</span>`;const d=dateOf(n.iso);$('#nowLabel').textContent=`${dayNames[d.getDay()]} · ${d.getDate()} ${months[d.getMonth()]} · ${String(n.hour).padStart(2,'0')}:${n.minute} bangkok`}
function weekStart(iso){const d=dateOf(iso),offset=(d.getDay()+6)%7;d.setDate(d.getDate()-offset);return d}
function renderToday(){const today=workouts.find(w=>w.date===todayIso);const next=[...workouts].filter(w=>w.date>todayIso).sort((a,b)=>a.date.localeCompare(b.date))[0];let state=today?today.title:'rest day';let detail=today?`${today.time} · treadmill ${today.treadmill?.mode||'walk'} · ${today.treadmill?.amount||'—'} ${today.treadmill?.unit||'km'}`:'no workout today. recover, reset, come back stronger.';let nextMarkup=next?`<span>next · ${dayNames[dateOf(next.date).getDay()]} ${dateOf(next.date).getDate()} ${months[dateOf(next.date).getMonth()]} · ${next.time}</span><button data-open="${next.id}">${next.title} →</button>`:'<span>no upcoming workouts</span><button data-create="true">add one →</button>';$('#todayCard').innerHTML=`<div><div class="today-label">today</div><div class="today-state">${lower(state)}</div><p class="today-detail">${lower(detail)}</p></div><div class="next-line">${nextMarkup}</div>`;$('#todayCard [data-open]')?.addEventListener('click',e=>openWorkout(e.currentTarget.dataset.open));$('#todayCard [data-create]')?.addEventListener('click',()=>openCreate(todayIso))}
function renderWeek(){const start=new Date(weekCursor),end=new Date(start);end.setDate(start.getDate()+6);$('#weekRange').textContent=`${start.getDate()}–${end.getDate()} ${months[end.getMonth()]}`;$('#weekStrip').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const iso=isoOf(d),w=workouts.find(x=>x.date===iso);return `<div class="day ${iso===todayIso?'today':''}" data-date="${iso}"><div class="day-name">${dayNames[d.getDay()]}</div><div class="day-num">${d.getDate()}</div>${w?`<div draggable="true" class="workout-pip ${w.type}" data-workout="${w.id}">${w.time}<br>${lower(w.title)}</div>`:''}</div>`}).join('');bindCalendarInteractions('#weekStrip .day')}
function renderCalendar(){const year=calendarCursor.getFullYear(),month=calendarCursor.getMonth();$('#calendarMonth').textContent=`${months[month]} '${String(year).slice(-2)}`;let html=['mon','tue','wed','thu','fri','sat','sun'].map(d=>`<div class="calendar-head">${d}</div>`).join('');const first=new Date(year,month,1,12),offset=(first.getDay()+6)%7;for(let i=0;i<42;i++){const d=new Date(year,month,1-offset+i,12),iso=isoOf(d),w=workouts.find(x=>x.date===iso);html+=`<div class="calendar-day ${d.getMonth()!==month?'outside':''} ${iso===todayIso?'today':''}" data-date="${iso}"><span class="day-number">${d.getDate()}</span>${w?`<div draggable="true" class="calendar-workout ${w.type}" data-workout="${w.id}">${w.time} · ${lower(w.title)}</div>`:''}</div>`}$('#calendar').innerHTML=html;bindCalendarInteractions('#calendar .calendar-day')}
function bindCalendarInteractions(selector){$$(selector).forEach(day=>{day.addEventListener('click',e=>{if(Date.now()<suppressClickUntil)return;const item=e.target.closest('[data-workout]');item?openWorkout(item.dataset.workout):openCreate(day.dataset.date)});day.addEventListener('dragover',e=>{e.preventDefault();day.classList.add('drag-over')});day.addEventListener('dragleave',()=>day.classList.remove('drag-over'));day.addEventListener('drop',e=>{e.preventDefault();day.classList.remove('drag-over');moveWorkout(draggedId,day.dataset.date)})});$$(`${selector} [data-workout]`).forEach(item=>{item.addEventListener('dragstart',e=>{draggedId=item.dataset.workout;e.dataTransfer.effectAllowed='move';e.stopPropagation()});item.addEventListener('dragend',()=>{draggedId=null;$$('.drag-over').forEach(x=>x.classList.remove('drag-over'))});bindTouchDrag(item)})}
function bindTouchDrag(item){const finish=e=>{if(!touchDrag||touchDrag.pointerId!==e.pointerId)return;clearTimeout(touchDrag.timer);const wasActive=touchDrag.active,target=touchDrag.target;item.classList.remove('touch-dragging');item.style.transform='';$$('.drag-over').forEach(x=>x.classList.remove('drag-over'));touchDrag=null;draggedId=null;if(wasActive){suppressClickUntil=Date.now()+450;if(target)moveWorkout(item.dataset.workout,target.dataset.date)}};item.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;const state={pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,active:false,target:null,timer:null};state.timer=setTimeout(()=>{state.active=true;draggedId=item.dataset.workout;item.classList.add('touch-dragging');navigator.vibrate?.(18)},320);touchDrag=state;item.setPointerCapture?.(e.pointerId)});item.addEventListener('pointermove',e=>{if(!touchDrag||touchDrag.pointerId!==e.pointerId)return;const dx=e.clientX-touchDrag.startX,dy=e.clientY-touchDrag.startY;if(!touchDrag.active&&Math.hypot(dx,dy)>10){clearTimeout(touchDrag.timer);touchDrag=null;return}if(!touchDrag.active)return;e.preventDefault();item.style.transform=`translate(${dx}px,${dy}px) scale(1.18)`;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.day,.calendar-day');if(target!==touchDrag.target){touchDrag.target?.classList.remove('drag-over');target?.classList.add('drag-over');touchDrag.target=target}});item.addEventListener('pointerup',finish);item.addEventListener('pointercancel',finish)}
function moveWorkout(id,date){if(!id)return;const collision=workouts.find(w=>w.date===date&&w.id!==id);if(collision)return openWorkout(collision.id);const w=workouts.find(w=>w.id===id);if(w){w.date=date;persist();renderAll()}}
function renderAll(){setGreeting();renderToday();renderWeek();renderCalendar()}
function addExerciseRow(ex=['','','']){const frag=$('#exerciseTemplate').content.cloneNode(true),row=frag.querySelector('.exercise-row');row.querySelector('.ex-name').value=ex[0]||'';row.querySelector('.ex-sets').value=ex[1]||'';row.querySelector('.ex-reps').value=ex[2]||'';row.querySelector('.remove-ex').onclick=()=>{row.remove();markDirty()};$('#exerciseFields').append(frag)}
function formState(){return JSON.stringify({title:$('#workoutTitle').value.trim(),date:$('#workoutDate').value,time:$('#workoutTime').value,type:$('#workoutType').value,treadmill:{mode:$('#treadmillMode').value,amount:$('#treadmillAmount').value.trim(),unit:$('#treadmillUnit').value},exercises:$$('.exercise-row').map(r=>[r.querySelector('.ex-name').value.trim(),r.querySelector('.ex-sets').value,r.querySelector('.ex-reps').value]).filter(e=>e.some(Boolean))})}
function markDirty(){const dirty=formState()!==originalSnapshot;$('#saveWorkout').disabled=!dirty;return dirty}
function openCreate(date=todayIso){$('#workoutForm').dataset.id='';$('#modalKicker').textContent='new workout';$('#workoutTitle').value='';$('#workoutDate').value=date;$('#workoutTime').value='11:00';$('#workoutType').value='low';$('#treadmillMode').value='walk';$('#treadmillAmount').value='';$('#treadmillUnit').value='km';$('#exerciseFields').innerHTML='';addExerciseRow();$('#deleteWorkout').hidden=true;$('#workoutDialog').showModal();originalSnapshot=formState();markDirty();setTimeout(()=>$('#workoutTitle').focus(),50)}
function openWorkout(id){const w=workouts.find(w=>w.id===id);if(!w)return;$('#workoutForm').dataset.id=id;$('#modalKicker').textContent='workout details';$('#workoutTitle').value=w.title;$('#workoutDate').value=w.date;$('#workoutTime').value=w.time;$('#workoutType').value=w.type;$('#treadmillMode').value=w.treadmill?.mode||'walk';$('#treadmillAmount').value=w.treadmill?.amount||'';$('#treadmillUnit').value=w.treadmill?.unit||'km';$('#exerciseFields').innerHTML='';w.exercises.forEach(addExerciseRow);$('#deleteWorkout').hidden=false;$('#workoutDialog').showModal();originalSnapshot=formState();markDirty()}
function saveCurrent(){const data=JSON.parse(formState()),id=$('#workoutForm').dataset.id;if(!data.title)data.title=data.type==='recovery'?'recovery session':`${data.type} intensity`;data.exercises=data.exercises.map(e=>[e[0],Number(e[1])||1,e[2]||'1']);if(id){Object.assign(workouts.find(w=>w.id===id),data)}else{data.id=`w${Date.now()}`;workouts.push(data)}persist();originalSnapshot=formState();$('#workoutDialog').close();renderAll()}
function requestClose(){if(markDirty()){pendingClose=true;$('#discardDialog').showModal()}else $('#workoutDialog').close()}
$('#workoutForm').addEventListener('input',markDirty);$('#workoutForm').addEventListener('change',markDirty);$('#workoutForm').addEventListener('submit',e=>e.preventDefault());$('#addExercise').onclick=()=>{addExerciseRow();markDirty()};$('#saveWorkout').onclick=saveCurrent;$('#closeModal').onclick=requestClose;$('#workoutDialog').addEventListener('cancel',e=>{e.preventDefault();requestClose()});$('#discardChanges').onclick=()=>{originalSnapshot=formState();$('#discardDialog').close();$('#workoutDialog').close();pendingClose=false};$('#saveChanges').onclick=()=>{$('#discardDialog').close();saveCurrent();pendingClose=false};$('#deleteWorkout').onclick=()=>{const id=$('#workoutForm').dataset.id;workouts=workouts.filter(w=>w.id!==id);persist();originalSnapshot=formState();$('#workoutDialog').close();renderAll()};$('#quickAdd').onclick=()=>openCreate(todayIso);$('#prevWeek').onclick=()=>{weekCursor.setDate(weekCursor.getDate()-7);renderWeek()};$('#nextWeek').onclick=()=>{weekCursor.setDate(weekCursor.getDate()+7);renderWeek()};$('#prevMonth').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1,12);renderCalendar()};$('#nextMonth').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1,12);renderCalendar()};
renderAll();
